### ISSUE TITLE
Convert JShint to ESlint and follow airbnb config

### ISSUE THREAD

**Issue by rcodonnell** [rcodonnell/AngularJS-CLI#15]
Currently code is standardized using jshint. ESlint is a more preferred method. Airbnb's javascript standards are one of the most popular standards to follow.
https://github.com/airbnb/javascript

#### Acceptance Criteria
* ESlint is setup and covers all JavaScript code client (currently es5) and server (currently es6)
* Build fails if code does not meet standards

**Comment by shakeelmohamed** [comment]
I'll take this! 🎃
