### ISSUE TITLE
Bring code up to new eslint standard

### ISSUE THREAD

**Issue by rcodonnell** [rcodonnell/AngularJS-CLI#18]
@shakeelmohamed I created a new ticket for you to finish those tasks if you wanted, else I can fix the code

**Comment by shakeelmohamed** [comment]
Go for it 😄  TODOs are listed in #17

**Comment by dhruvdutt** [comment]
Can I do it? @rcodonnell

**Comment by rcodonnell** [comment]
@dhruvdutt yeah sure
