### ISSUE TITLE
Setup Scss

### ISSUE THREAD

**Issue by rcodonnell** [rcodonnell/AngularJS-CLI#2]

**Comment by REPTILEHAUS** [comment]
What exactly do you require with scss setup ? any further details would be great.

**Comment by rcodonnell** [comment]
npm to compile the sass from a style folder and direct it to the dist folder.

**Comment by REPTILEHAUS** [comment]
Would a gulp script work ? have it compile from /app/layout/scss/ to /app/layout/css/

**Comment by rcodonnell** [comment]
I am trying to stay away from any task managers for this. I was planning on setting it all to just use npm scripts. So the folder structure would be
/root/
 - /app/
 --- app.js
 --- /layout/ all javascript
 - /styles/
 --- app.scss 
 --- /modules/ all scss
 - /dist/all compiled code

**Comment by sschadwick** [comment]
PR submitted
