### ISSUE TITLE
Create install script to install base angular into a folder

### ISSUE THREAD

**Issue by rcodonnell** [rcodonnell/AngularJS-CLI#6]
Currently there is no script to install the files into someone's working directory or repo.

There needs to be a script to install it

**Comment by wmadisonDev** [comment]
Have you considered https://github.com/angular/angular-cli?

**Comment by rcodonnell** [comment]
@wmadisonDev
That is for angular 2, I am trying to build up be for angular 1.5 and I just kinda wanted to build one myself for my own experience

**Comment by matthamil** [comment]
I can work on a Bash script to get it installed for a user's project. Or are you looking for something to be hosted on npm?

**Comment by rcodonnell** [comment]
Plans for better script in the future, Closing this now
